[package]
name = "viu"
version = "1.3.0"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
categories = ["command-line-utilities"]
keywords = ["terminal", "image", "gif"]
exclude = ["/img", "/.github"]

[dependencies]
clap = "2.33"
crossterm = "0.19"
viuer = "0.4"
ctrlc = { version = "3.1", features = ["termination"] }
image = "0.23"
