[package]
name = "viu"
version = "0.2.1"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
exclude = ["img/*"]

[dependencies]
libc = "0.2"
clap = "2.32.0"
termcolor = "1"
gif = "0.10.1"

# [target.'cfg(not(any(linux, unix)))'.dependencies]
image = { version = "0.21.1", default-features = false, features = ["gif_codec", "jpeg", "ico", "jpeg-decoder", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"] }

[target.'cfg(any(linux, unix))'.dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
# image = "0.21.1"
